apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end

spec:
  template: # below is where you add your Pod, you add everything expect for apiVersion and kind

    metadata:
      name: myapp-pod
      label:
        app: myapp
        type: front-end
      spec:
        containers:
        - name: nginx-container
          image: nginx

  replicas: 3