kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: PVC-NAME
spec:
  storageClassName: manual
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi