# This is used to  request storage space
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: PVC-NAME
spec:
  storageClassName: manual # make sure you have this
  volumeMode: Filesystem # This is how volume should be mounted so this mean it will appear as a regular file system
  accessModes:
    - ReadWriteOnce # Only one node can read or write
  resources:
    requests: # the minimum amount of resources it needs
      storage: 10Gi # This storage