# This is telling Kubernetes that you want to create a special storage space for your application.
#It's backed by NFS which is something seperate from Kubernetes and Kubernetes access it when it needs to so it not in the cluser
apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv-name #The name to our storage space
spec: # Giving the details to our storage space
  capacity:
     storage: 5Gi # This line set how big the storage space is
  volumeMode: Filesystem # This mean you want the storage to be organized in a hierarchical structure
  #similar to how files are
  accessModes:
    - ReadWriteOnce # Only one user at a time can read or write
  persistentVolumeReclaimPolicy: Recycle # Telling kubernetes to clean and make it readt for someone else when i am done
  storageClassName: slow # Just a class name
  mountOptions:
    - hard # It will keep trying when there is a problem
    - nfsvers=4.1 # Giving the version of the NFS protocol to use
  nfs:
    path: /dir/path/on/nfs/server # This part tell Kubernetes where the storage is located and where to find it
    server: nfs-server-ip-address
