apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec: # This is the specification of the service
  # ClusterIP is has a static IP address and is used for internal communication within the cluster and to the pods
  type: ClusterIP # This is the type of service
  ports:
    - targetPort: 80 # This is the port that the service will forward to and is where your application is
      port: 80 # This is the port that the service will listen to when your inside the cluster

  selector:
    app: myapp
    type: front-end