# This YAML file define a pod that has a single container.
#The Pod demonstrates two ways to use a Secret named mysecret
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - name: exapmple
      image: nginx
      # This is to get as an environment variable
      env:
        - name: SECRET_FILE
          valueFrom:
            secretKeyRef:
              name: secret-file # This is the name of the secret that's named in metadata
              key: secret.file # This is the key of the secret that's named in data that we want to use
      volumeMounts: # This is saving the file onto the container file system
        - name: secret-volume
          mountPath: /etc/secret # This is the path where the volume will be located in the pod
          readOnly: true
  volumes: # This is fetching the file from the secret and putting it in a volume
    - name: secret-volume
      secret:
        secretName: secret-file

