# This YAML file define a pod that has a single container.
#The Pod demonstrates two ways to use a Secret named mysecret
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - name: exapmple
      image: nginx
      env:
        - name: MY_SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password

