# This YAML file define a pod that has a single container.
#The Pod demonstrates two ways to use a Secret named mysecret
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - name: exapmple
      image: nginx
      env:
        - name: SECRET_FILE
          valueFrom:
            secretKeyRef:
              name: secret-file
              key: secret.file
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: secret-file

